services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smartcity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:localpassword123@db:5432/smartcity
      DEBUG: "True"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000/api

  pipeline:
    build: ./pipeline
    volumes:
      - ./pipeline:/app
    environment:
      DATABASE_URL: postgresql://postgres:localpassword123@db:5432/smartcity
      OPENWEATHER_API_KEY: 486af2d663884acd198647a31cf757e9
    depends_on:
      - db

  ml_service:
    build: ./ml
    volumes:
      - ./ml:/app
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://postgres:localpassword123@db:5432/smartcity
    depends_on:
      - db

volumes:
  postgres_data:
